"""Python port of docs/calc.js (cash buy-vs-rent). Kept in lockstep; tests/test_buyrent.py
checks parity against numbers generated by the JS engine."""
from __future__ import annotations

from dataclasses import dataclass, replace


@dataclass
class Params:
    price: float = 2_500_000
    rent: float = 7_000
    years: int = 7
    opp_rate: float = 0.07
    opp_tax_mode: str = "deferred"
    fed_rate: float = 0.24
    ca_rate: float = 0.093
    ltcg_fed_rate: float = 0.15
    ltcg_high_rate: float = 0.20
    ltcg_top: float = 613_700
    ordinary_taxable: float = 298_000
    niit_rate: float = 0.038
    prop_tax_rate: float = 0.012
    prop13_cap: float = 0.02
    insurance: float = 10_000
    earthquake: float = 0
    maint_rate: float = 0.01
    hoa: float = 0
    buy_close: float = 0.01
    sell_close: float = 0.058
    rent_growth: float = 0.03
    appreciation: float = 0.03
    expense_inflation: float = 0.03
    cg_exclusion: float = 500_000


def from_config(cfg_br: dict, **overrides) -> Params:
    known = {k: v for k, v in cfg_br.items() if k in Params.__dataclass_fields__}
    known.update(overrides)
    return Params(**known)


def capital_gains_tax(p: Params, gain: float) -> float:
    if gain <= 0:
        return 0.0
    room = max(0.0, p.ltcg_top - p.ordinary_taxable)
    low = min(gain, room)
    high = gain - low
    return low * p.ltcg_fed_rate + high * p.ltcg_high_rate + gain * (p.niit_rate + p.ca_rate)


def portfolio_growth(p: Params) -> float:
    return p.opp_rate * (1 - p.fed_rate) if p.opp_tax_mode == "annual" else p.opp_rate


def sale_net(p: Params, value: float) -> float:
    proceeds = value * (1 - p.sell_close)
    gain = proceeds - p.price * (1 + p.buy_close)
    taxable = max(0.0, gain - p.cg_exclusion)
    return proceeds - capital_gains_tax(p, taxable)


def final_diff(p: Params) -> float:
    w0 = p.price * (1 + p.buy_close)
    value = assessed = p.price
    port = basis = w0
    g = portfolio_growth(p)
    diff = 0.0
    for y in range(1, p.years + 1):
        infl = (1 + p.expense_inflation) ** (y - 1)
        rent = p.rent * 12 * (1 + p.rent_growth) ** (y - 1)
        own = assessed * p.prop_tax_rate + (p.insurance + p.earthquake) * infl + value * p.maint_rate + p.hoa * 12 * infl
        contribution = own - rent
        port = port * (1 + g) + contribution
        basis += contribution
        value_end = value * (1 + p.appreciation)
        renter_net = port - capital_gains_tax(p, port - basis) if p.opp_tax_mode == "deferred" else port
        diff = sale_net(p, value_end) - renter_net
        value = value_end
        assessed = min(assessed * (1 + p.prop13_cap), value)
    return diff


def _solve(f, lo: float, hi: float, steps: int) -> float | None:
    prev_x, prev_y = lo, f(lo)
    for i in range(1, steps + 1):
        x = lo + (hi - lo) * i / steps
        y = f(x)
        if prev_y == 0:
            return prev_x
        if (prev_y < 0) != (y < 0):
            a, b, fa = prev_x, x, prev_y
            for _ in range(60):
                m = (a + b) / 2
                fm = f(m)
                if (fm < 0) == (fa < 0):
                    a, fa = m, fm
                else:
                    b = m
            return (a + b) / 2
        prev_x, prev_y = x, y
    return None


def breakeven_price(p: Params) -> float | None:
    return _solve(lambda x: final_diff(replace(p, price=x)), 200_000, 20_000_000, 200)


def rent_equivalent(p: Params) -> float | None:
    return _solve(lambda x: final_diff(replace(p, rent=x)), 500, 60_000, 240)
